<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="actionpak1"
    nsURI="http:///com/safi/workshop/actionpak1.ecore" nsPrefix="com.safi.workshop.actionpak1">
  <eClassifiers xsi:type="ecore:EClass" name="ActionstepTest" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ActionStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="message" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Saflet Path"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="The message to be logged"/>
        <details key="expectedReturnType" value="Saflet Path"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
      <eAnnotations source="Required">
        <details key="criteria" value="non-null"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CustomInitiator" abstract="true" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ParameterizedInitiator"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncomingCall2" abstract="true" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ParameterizedInitiator ../../Saflets/model/core.ecore#//call/CallSource1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="callName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeSaflet2" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ParameterizedActionstep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetSafletPath" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Saflet Path"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="The path of the handler to which control will be transferred"/>
        <details key="expectedReturnType" value="Saflet Path"/>
        <details key="helperClass" value="com.safi.workshop.sheet.SelectSafletDynamicValueEditorPage"/>
      </eAnnotations>
      <eAnnotations source="Required">
        <details key="criteria" value="non-null"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelText" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScheduleSaflet" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ParameterizedActionstep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobNamePrefix" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Text"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="Optional (unique) name to be assigned to the job "/>
        <details key="expectedReturnType" value="Text"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetSafletPath" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Saflet Path"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="The path of the handler to which control will be transferred"/>
        <details key="expectedReturnType" value="Saflet Path"/>
        <details key="helperClass" value="com.safi.workshop.sheet.SelectSafletDynamicValueEditorPage"/>
      </eAnnotations>
      <eAnnotations source="Required">
        <details key="criteria" value="non-null"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cronExpression" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Text"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="Cron expression defining the saflet execution schedule"/>
        <details key="expectedReturnType" value="Crontab Expr"/>
        <details key="helperClass" value="com.safi.workshop.sheet.ScheduledSafletDynamicValueEditorPage"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="startDateTime" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="DateTime"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="Start DateTime for the the saflet execution schedule"/>
        <details key="expectedReturnType" value="VariableName"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="endDateTime" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="DateTime"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="End DateTime for the the saflet execution schedule"/>
        <details key="expectedReturnType" value="VariableName"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calendarName" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Text"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="Calendar name for the saflet execution schedule"/>
        <details key="expectedReturnType" value="Text"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobName" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="VariableName"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="The unique name of the job that was created"/>
        <details key="expectedReturnType" value="Text"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
      <eAnnotations source="Directionality">
        <details key="output" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnscheduleSaflet" eSuperTypes="../../Saflets/model/core.ecore#//actionstep/ActionStep">
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobName" ordered="false"
        eType="ecore:EClass ../../Saflets/model/core.ecore#//actionstep/DynamicValue"
        containment="true" resolveProxies="false">
      <eAnnotations source="DynamicValueAnnotation">
        <details key="type" value="Text"/>
        <details key="isTypeLocked" value="false"/>
        <details key="description" value="Name of the job to be unscheduled"/>
        <details key="expectedReturnType" value="VariableName"/>
        <details key="helperClass" value=""/>
      </eAnnotations>
      <eAnnotations source="Required">
        <details key="criteria" value="non-null"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
